import yfinance as yf
import feedparser
from datetime import datetime
from pathlib import Path

STOCKS = Path("stocks.txt").read_text().strip().splitlines()

def get_yahoo_news(ticker):
    url = f"https://feeds.finance.yahoo.com/rss/2.0/headline?s={ticker}&region=US&lang=en-US"
    feed = feedparser.parse(url)
    return [
        {"title": e.title, "link": e.link, "published": e.get("published", "")}
        for e in feed.entries[:5]
    ]

def get_stock_info(ticker):
    try:
        t = yf.Ticker(ticker)
        info = t.info
        hist = t.history(period="2d")
        price = hist["Close"].iloc[-1] if not hist.empty else None
        prev  = hist["Close"].iloc[-2] if len(hist) > 1 else price
        change_pct = ((price - prev) / prev * 100) if price and prev else 0
        return {
            "name": info.get("longName", ticker),
            "price": round(price, 2) if price else "N/A",
            "change_pct": round(change_pct, 2),
            "sector": info.get("sector", "N/A"),
        }
    except:
        return {"name": ticker, "price": "N/A", "change_pct": 0, "sector": "N/A"}

def generate_html(data):
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    rows = ""
    for item in data:
        info = item["info"]
        color = "green" if info["change_pct"] >= 0 else "red"
        sign  = "+" if info["change_pct"] >= 0 else ""
        news_html = "".join(
            f'<li><a href="{n["link"]}" target="_blank">{n["title"]}</a> <small>{n["published"][:16]}</small></li>'
            for n in item["news"]
        ) or "<li>No news found</li>"
        rows += f"""
        <div class="card">
          <div class="card-header">
            <span class="ticker">{item['ticker']}</span>
            <span class="name">{info['name']}</span>
            <span class="price">${info['price']}</span>
            <span class="change" style="color:{color}">{sign}{info['change_pct']}%</span>
          </div>
          <div class="meta">Sector: {info['sector']}</div>
          <ul class="news-list">{news_html}</ul>
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stock News Report</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; background: #f5f5f5; }}
    h1 {{ color: #1a1a2e; }}
    small {{ color: #666; font-size: 0.85em; }}
    .card {{ background: white; border-radius: 10px; padding: 20px; margin: 16px 0; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
    .card-header {{ display: flex; align-items: center; gap: 16px; flex-wrap: wrap; margin-bottom: 8px; }}
    .ticker {{ font-size: 1.4em; font-weight: 700; color: #1a1a2e; }}
    .name {{ color: #555; flex: 1; }}
    .price {{ font-size: 1.2em; font-weight: 600; }}
    .change {{ font-weight: 600; }}
    .meta {{ color: #888; font-size: 0.85em; margin-bottom: 10px; }}
    .news-list {{ padding-left: 18px; }}
    .news-list li {{ margin: 6px 0; }}
    .news-list a {{ color: #0066cc; text-decoration: none; }}
    .news-list a:hover {{ text-decoration: underline; }}
    footer {{ text-align: center; color: #aaa; margin-top: 40px; font-size: 0.85em; }}
  </style>
</head>
<body>
  <h1>📈 Stock News Report</h1>
  <p><small>Generated: {now} | Stocks: {len(data)}</small></p>
  {rows}
  <footer>Auto-generated by GitHub Actions · Source: Yahoo Finance</footer>
</body>
</html>"""

if __name__ == "__main__":
    data = []
    for ticker in STOCKS:
        print(f"Processing {ticker}...")
        data.append({
            "ticker": ticker,
            "info": get_stock_info(ticker),
            "news": get_yahoo_news(ticker),
        })
    Path("report").mkdir(exist_ok=True)
    Path("report/index.html").write_text(generate_html(data))
    print("Done! Report saved to report/index.html")
